### ISSUE TITLE
Build FAILED

### ISSUE THREAD

**Issue by gynaryon** [kairosinc/kairos-emotion-sdk-csharp#1]
I followed the instruction but got the following build failure:

/var/tmp/kairos-emotion-sdk-csharp/KairosEmotionAPI.PCL/KairosEmotionAPI.PCL.csproj (Build) ->
/Library/Frameworks/Mono.framework/Versions/4.2.1/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

```
Controllers/EmotionAnalysisController.cs(84,12): error CS1525: Unexpected symbol `HttpRequest'
Controllers/EmotionAnalysisController.cs(138,12): error CS1525: Unexpected symbol `HttpRequest'
Controllers/EmotionAnalysisController.cs(192,12): error CS1525: Unexpected symbol `HttpRequest'

 0 Warning(s)
 3 Error(s)
```

Please help.

**Comment by AsgerJ** [comment]
Maybe you can escalate to APIMATIC (https://apimatic.io) as mentioned in the license and the readme. Good luck!

**Comment by kand617** [comment]
Hi @coleca, I am Kartik from APIMATIC. 

I noticed that this is no longer a issue on the latest codegen.
Perhaps you would like to regenerate the SDK. 

Thanks
Kartik

**Comment by coleca** [comment]
Thanks @kand617 we will do that...

**Comment by coleca** [comment]
Regenerated, thanks @kand617

**Comment by gynaryon** [comment]
Thanks for the update but we've used another C# SDK to accomplish our project.
